// <copyright file="Environment.cs" company="APIMatic">
// APIMATICCalculatorZip.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace APIMATICCalculatorZip.Standard
{
    /// <summary>
    /// Available environments.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Environment
    {
        /// <summary>
        /// This environment connect to the LIVE calculator API.
        /// </summary>
        [EnumMember(Value = "production")]
        Production,
    }
}
